### ISSUE TITLE
OHC fails to load on 1.7 Zing VM

### ISSUE THREAD

**Issue by aweisberg** [snazy/ohc#10]
See https://issues.apache.org/jira/browse/CASSANDRA-9296

**Comment by mebigfatguy** [comment]
In Uns.java of version 0.3.4 line 158 you catch an exception after attempting to use the java 8 class, and fall back to the java 7 class. however, java throws an Error, not an Exception..

UnsupportedClassVersionError

seems like you should just check system property "java.version"
