### ISSUE TITLE
solaris sparc x64 crash unsafe putLong

### ISSUE THREAD

**Issue by vharseko** [snazy/ohc#16]
A fatal error has been detected by the Java Runtime Environment:

  SIGBUS (0xa) at pc=0xffffffff7e46b840, pid=10528, tid=827

 JRE version: Java(TM) SE Runtime Environment (8.0_45-b14) (build 1.8.0_45-b14)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode solaris-sparc compressed oops)
 Problematic frame:
 V  [libjvm.so+0xc6b840]  Unsafe_SetLong+0x160

 Core dump written. Default location: /opt/cassandra/core or core.10528

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp

Stack: [0xfffffff8d0e00000,0xfffffff8d0e40000],  sp=0xfffffff8d0e3dd20,  free space=247k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xc6b840]  Unsafe_SetLong+0x160
J 3554  sun.misc.Unsafe.putLong(Ljava/lang/Object;JJ)V (0 bytes) @ 0xffffffff6cfa814c [0xffffffff6cfa7fe0+0x16c]
j  org.caffinitas.ohc.linked.Uns.putLong(JJJ)V+17
j  org.caffinitas.ohc.linked.HashEntryValueOutput.writeLong(J)V+15
j  org.apache.cassandra.cache.OHCProvider$ValueSerializer.serialize(Lorg/apache/cassandra/cache/IRowCacheEntry;Ljava/io/DataOutput;)V+42
j  org.apache.cassandra.cache.OHCProvider$ValueSerializer.serialize(Ljava/lang/Object;Ljava/io/DataOutput;)V+6
j  org.caffinitas.ohc.linked.OHCacheImpl.serializeForPut(Ljava/lang/Object;Ljava/lang/Object;JJJ)J+45
j  org.caffinitas.ohc.linked.OHCacheImpl.putInternal(Ljava/lang/Object;Ljava/lang/Object;ZLjava/lang/Object;)Z+240
j  org.caffinitas.ohc.linked.OHCacheImpl.putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Z+5
j  org.apache.cassandra.cache.OHCProvider$OHCacheAdapter.putIfAbsent(Lorg/apache/cassandra/cache/RowCacheKey;Lorg/apache/cassandra/cache/IRowCacheEntry;)Z+6
j  org.apache.cassandra.cache.OHCProvider$OHCacheAdapter.putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Z+9
j  org.apache.cassandra.cache.InstrumentingCache.putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Z+6
j  org.apache.cassandra.db.ColumnFamilyStore.getThroughCache(Ljava/util/UUID;Lorg/apache/cassandra/db/filter/QueryFilter;)Lorg/apache/cassandra/db/ColumnFamily;+236
j  org.apache.cassandra.db.ColumnFamilyStore.getColumnFamily(Lorg/apache/cassandra/db/filter/QueryFilter;)Lorg/apache/cassandra/db/ColumnFamily;+89
j  org.apache.cassandra.db.Keyspace.getRow(Lorg/apache/cassandra/db/filter/QueryFilter;)Lorg/apache/cassandra/db/Row;+11
j  org.apache.cassandra.db.SliceFromReadCommand.getRow(Lorg/apache/cassandra/db/Keyspace;)Lorg/apache/cassandra/db/Row;+222
j  org.apache.cassandra.db.ReadVerbHandler.doVerb(Lorg/apache/cassandra/net/MessageIn;I)V+39
j  org.apache.cassandra.net.MessageDeliveryTask.run()V+82

**Comment by snazy** [comment]
Thanks for reporting. I assume that Cassandra's row cache serializer is just incompatible with Sparc CPU architecture, which requires 8-byte aligned memory accesses. The right place to fix this would be in OHC and special case the code in `Uns` for CPU architectures that require aligned memory accesses. Unfortunately I do not have access to such a machine.

**Comment by snazy** [comment]
Revisited this ticket. @vharseko mind to recheck this with a Cassandra 3.0 or newer? The OHC API has been refactored from streams to `ByteBuffer` in OHC 0.4, which is used in C* 3.0 and newer. C* 2.2 however still uses the old API, which causes this issue to occur.
