### ISSUE TITLE
Checking for java 8 fails

### ISSUE THREAD

**Issue by br1985** [snazy/ohc#17]
Here's the Cassandra warning I see during startup:

    WARN  [main] 2016-02-10 00:05:42,094 Uns.java:169 - Failed to load Java8 implementation ohc-core-j8 : java.lang.NoSuchMethodException: org.caffinitas.ohc.linked.UnsExt8.<init>(java.lang.Class)

The `NoSuchMethodException` seems to be caused by the former of these two lines in `Uns.java`:

    Class<? extends UnsExt> cls = (Class<? extends UnsExt>) Class.forName(UnsExt7.class.getName().replace('7', '8'));
    e = cls.getDeclaredConstructor(Class.class).newInstance(unsafe);`

The first one works fine. Object representing class `UnsExt8` is correctly assigned to `cls` variable.

The problem is with method `getDeclaredConstructor`. Class `UnsExt8` does NOT have a declared constructor with a single parameter of type `Class`, so the method throws `NoSuchMethodException` (exactly as one may expect).

Changing the second line to:

    e = cls.getDeclaredConstructor(Unsafe.class).newInstance(unsafe);`

seems to fix the issue. This was the original version. It was changed here:

https://github.com/snazy/ohc/commit/a268e00b66a99423d0af045560d6bfb2f39adc44

Am I missing anything here? How is this supposed to work?

I observe the same issue outside of Cassandra context too. This simple test with any dummy cacheSerializer exposes the problem:

    OHCache ohCache = OHCacheBuilder.newBuilder()
        .keySerializer(cacheSerializer)
        .valueSerializer(cacheSerializer)
        .build();
    ohCache.clear();

I've tried with Oracle 1.8.0u74 and OpenJDK 1.8.0u66 and 1.8.0u72.

**Comment by snazy** [comment]
Thanks for reporting. I think your conclusion is correct and is easy to fix.

**Comment by snazy** [comment]
Fixed. Thanks for reporting!
