### ISSUE TITLE
getWithLoader needs contract for null/non-existant values

### ISSUE THREAD

**Issue by oobles** [snazy/ohc#23]
When using the getWithLoader for a key that doesn't exist, the value is still passed to the serializedSize method.   Would it be better to check for null values and not store null entries?

Line 395:
                      try
                        {
                            value = loader.load(key);

                            long entryExpireAt = expireAt;
                            if (entryExpireAt > 0L && entryExpireAt <= System.currentTimeMillis())
                            {
                                segment.removeEntry(sentinelHashEntryAdr);

                                // already expired
                                return null;
                            }

                            // not already expired

                            long valueLen = valueSerializer.serializedSize(value);

**Comment by snazy** [comment]
Hm - yes and no. But the point you're raising is a good catch. The API does not define a contract how to deal with null values / how to deal with non-existing entries. Need to fix that.

**Comment by oobles** [comment]
Found out the hard way about the contract. :)

Interestingly, the Cache will call the value serializer serializeSize with a null value and allocate a buffer based on the return value.  However, if the value is null the serialize method will not be called.   To handle null values and this behaviour, I implemented the following:

    // serializedSize returns 0 for a null entry.
    public int serializedSize(final T t) {
        int size = 0;
        if (t != null) {
            size = customerSizeCalculator(t);
        }
        return size;
    }

// deserialize.  If the capacity is 0 then entry is null value.
public T deserialize(final ByteBuffer buf) {
            T value = null;
            final int isEmptyBuffer = buf.capacity();
            if (isEmptyBuffer != 0) {
                value = performCustomDeserialze(buf);
            }
            return value;
    }

**Comment by snazy** [comment]
Well, `null` values are not permitted by all other methods. I think the original intention was to allow some "negative" caching - but it does not feel right the way it's implemented.

**Comment by snazy** [comment]
I think the solution is to handle `null` early and just return `null`. Committed and pushed that to the develop branch.
