### ISSUE TITLE
RuntimeException for getWithLoader

### ISSUE THREAD

**Issue by oobles** [snazy/ohc#24]
In the Linked/OHCacheImpl the getWithLoader has two conditions that will cause a runtime exception.  Would it be better to delete anything from the cache, log a warning and return the loaded value rather than throw a RuntimeException?

Lines from 414 to 426 of OHCacheImpl:

                            if ((maxEntrySize > 0L && bytes > maxEntrySize) || (hashEntryAdr = Uns.allocate(bytes, throwOOME)) == 0L) {
                                // Remove key, log warning and return loaded value instead?
                                throw new RuntimeException("max entry size exceeded or malloc() failed");
                           }

                            long hash = serializeForPut(key, value, keyLen, valueLen, hashEntryAdr);
                            if (entryExpireAt == -1L)
                                entryExpireAt = defaultExpireAt();

                            // initialize hash entry
                            HashEntries.init(hash, keyLen, valueLen, hashEntryAdr, Util.SENTINEL_NOT_PRESENT, entryExpireAt);

                            if (!segment.replaceEntry(hash, sentinelHashEntryAdr, hashEntryAdr, bytes, entryExpireAt)) {
                               // Remove key, log warning and return loaded value instead?
                                throw new RuntimeException("not enough free capacity");
                            }
                            derefSentinel = true;

**Comment by snazy** [comment]
These `RuntimeExceptions` are only thrown if a severe error happened. Severe means that it was unable to allocate memory at all (which is pretty bad) or the sentinel could not be replaced internally (which would probably represents a race condition or bug).
Normal eviction rules apply in the call to `replaceEntry`.

Closing this issue for now. Feel free to reopen, if you think it is a bug.
