### ISSUE TITLE
OHC core tests failure

### ISSUE THREAD

**Issue by trepik** [snazy/ohc#25]
I'm building OHC for fedora-rawhide and while executing tests on ohc-core I'm sutck, getting this error message:
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-2.b14.fc26.x86_64/jre/bin/java: symbol lookup error: /tmp/snappy-1.1.2.4-a36a540c-a5ee-471b-a91c-a2ec39e1703e-libsnappyjava.so: undefined symbol: _ZN6snappy19MaxCompressedLengthEm

Do you have any Idea where the problem might be?
Thanks in advance, Tomas

**Comment by snazy** [comment]
Hm. Frankly, I don't. Can you try updating the `version.org.xerial.snappy` property in the parent `pom.xml` to e.g. `1.1.2.6` and see if that helps?

**Comment by trepik** [comment]
I tried it on versions `0.4.2` & `0.4.4`, with the same result.

**Comment by snazy** [comment]
0.4.2 and 0.4.4? What I meant is whether you can replace the line
```
        <version.org.xerial.snappy>1.1.1.7</version.org.xerial.snappy>
```
with
```
        <version.org.xerial.snappy>1.1.2.6</version.org.xerial.snappy>
```
in the upmost `pom.xml` and see whether that helps.

**Comment by snazy** [comment]
Oh, ok. I'll give Fedora Rawhide a try.

**Comment by snazy** [comment]
Hm. I just installed Fedora Rawhide in a VM (plus openjdk 1.8.0_101 + git) and built OHC without any issues - tests ran fine.

**Comment by trepik** [comment]
Hi, I came back to OHC after a while, but unfortunately the results are still the same (as above). I'm providing other part of the log mentioning error. Probably it will bring some light into the darkness.

ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project ohc-core: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /builddir/build/BUILD/ohc-0.5.1/ohc-core && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.102-2.b14.fc26.x86_64/jre/bin/java -jar /builddir/build/BUILD/ohc-0.5.1/ohc-core/target/surefire-reports/surefire/surefirebooter5557939803627432260.jar /builddir/build/BUILD/ohc-0.5.1/ohc-core/target/surefire-reports/surefire/surefire8910248000356901578tmp /builddir/build/BUILD/ohc-0.5.1/ohc-core/target/surefire-reports/surefire/surefire_04829306303414111535tmp

**Comment by snazy** [comment]
Can you provide the whole log files?

**Comment by trepik** [comment]
https://trepik.fedorapeople.org/tmp/ohc_build.log

**Comment by snazy** [comment]
Can you uninstall `snappy.x86_64 1.1.3-2.fc24` and `snappy-java.x86_64 1.1.2.4-2.fc25` and try again?

**Comment by trepik** [comment]
Obviously the build fail on missing dependency, when run without snappy installed
https://trepik.fedorapeople.org/tmp/ohc_build2.log

**Comment by trepik** [comment]
Today I tried once again building ohc-0.5.1 in [fedora-rawhide](http://koji.fedoraproject.org/koji/taskinfo?taskID=16281488) and there is still the same issue. Could someone have a look?

**Comment by snazy** [comment]
Tried it again using the following setup:
* Fedora Rawhide (server, net install, 4.8.6-201.fc24.x86_64)
* Oracle 8 (1.8.0_111)
* latest Maven for the build
* ohc from develop branch (contains some fixes I needed for my single-CPU VM)

All tests run fine.
I suspect there's something in your environment that causes the test to fail.

**Comment by trepik** [comment]
Fedora release 24 (Twenty Four) 4.8.4-200.fc24.x86_64
openjdk-1.8.0.111
maven-3.3.9-4.fc24.noarch
ohc-0.5.1 (latest release)

And I have a different output, some specific tests fail, can you have a look?
https://trepik.fedorapeople.org/tmp/err.log

**Comment by snazy** [comment]
Probably the unit tests fixed in the _develop_ branch.

**Comment by trepik** [comment]
Your fix actually worked but only with the old snappy-java. Please look for more info in the issue I posted in snappy-java repository [1]. I'll be glad if we can work this out.

[1] https://github.com/xerial/snappy-java/issues/150

**Comment by snazy** [comment]
Hm - yea. But it's just some fix in a unit test. No code or dependency change.
Will close this for now.

**Comment by trepik** [comment]
I've been looking into details of this issue. I'm more that sure that the issue is with the .so files, getting an error mentioned in the initial issue report.

I inspected different versions of libsnappy.so:

$ readelf -Ws /usr/lib64/libsnappy.so.1.3.0 | grep Max
     36: 0000000000002560    26 FUNC    GLOBAL DEFAULT   11 _ZN6snappy19MaxCompressedLengthEm
-> this is native snappy library version 1.1.3-2.fc24

$ readelf -Ws libsnappyjava-1.0.5-6.fc24.so | grep Max
     4: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND _ZN6snappy19MaxCompressedLengthEm
-> with this version of libsnappyjava.so everything works fine and there is no error

$ readelf -Ws libsnappyjava-1.1.1.7.so | grep maxC
   552: 0000000000016330    17 FUNC    GLOBAL DEFAULT   10 Java_org_xerial_snappy_SnappyNative_maxCompressedLength
-> this is the libsnappyjava.so from mavencentral, version 1.1.1.7 is the one used by upstream and as they could tell they don't see any issue

$ readelf -Ws libsnappyjava-1.1.2.4-2.fc25.so | grep Max
     4: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZN6snappy19MaxCompressedLengthEm
-> and finally this is the version causing  trouble and fails the ohc tests

**Comment by snazy** [comment]
Looks like Snappy picks up the wrong .so file. According to `org.xerial.snappy.SnappyLoader.loadNativeLibrary()`, it _should_ prefer the bundled .so.
Can you check whether a `libsnappy*.so` lands in `/tmp` (or whatever the temp-dir is)?
Oh, BTW, what are the values for the system properties `os.arch` and `os.name`? (You can get them via `java -XshowSettings:properties -version`)

**Comment by trepik** [comment]
Well it can't find the symbol in the bundled library (see [comment 1](https://github.com/snazy/ohc/issues/25#issue-168588142)). You can also see that the `.so` lands ins `/tmp` dir. What if I don't want to load the bundled library but my native one?

and BTW
os.arch = amd64
os.name = Linux

**Comment by snazy** [comment]
That's snappy stuff in `org.xerial.snappy.SnappyLoader#loadNativeLibrary` and `findNativeLibrary`:
* system property `org.xerial.snappy.use.systemlib=true` would force snappy to ignore the bundled lib. I.e. it simply uses `java.lang.System.loadLibrary("snappyjava")`
* system property `org.xerial.snappy.lib.path=/some/path` forces snappy to look into this directory for the .so
* system property `org.xerial.snappy.lib.name=libsnappy...so` forces snappy to look for this file

I.e. the best bet to force snappy to use a specific .so is to use the `org.xerial.snappy.lib.path/name` system properties.

**Comment by trepik** [comment]
Thanks for your help we figured out the linking and now the issues is fixed. However, I encountered a new error stating that my machine is too slow. Should I skip the tests and don't bother or is there some fix to prevent this error? 
`TimeoutsTest.testExpireVsEvict:173 Sorry, your machine is a bit too slow... expected [true] but found [false]`
