### ISSUE TITLE
replace ReentrantLock with CAS-lock

### ISSUE THREAD

**Issue by snazy** [snazy/ohc#27]
ReentrantLock is kind-of heavy compared to the operations that need to be performed in locked-state within OHC impl.

Therefore it's reasonable to replace ReentrantLock with AtomicLongUpdate and use CAS to lock (and use a spinning try-lock).

**Comment by snazy** [comment]
committed

**Comment by avukajlo** [comment]
Just to comment a usage of parkNanos
// "sleep" for 100ns - operations performed while the lock's being held
// may include "expensive" operations (secondary indexes for example).
LockSupport.parkNanos(100L);

parkNanos on windows jvm has millisec resolution. This concrete park will result in 1ms sleep (WaitForSingleObject winapi). Which is too much for this purpose. Better usage would be Thread.yield().
Good info on this: http://vanillajava.blogspot.rs/2012/04/yield-sleep0-wait01-and-parknanos1.html

**Comment by snazy** [comment]
ouch - that's bad. thanks for the heads-up

**Comment by snazy** [comment]
Just a note regarding the blog post you mentioned. The code examples in that post rely on `System.nanoTime()` which has its own downsides, as described here: https://shipilev.net/blog/2014/nanotrusting-nanotime/

Will investigate `LockSupport.parkNanos(long)` on different platforms.

**Comment by snazy** [comment]
Yup - seems that all OS use nanoseconds for `LockSupport.park` - except Windows, which uses milliseconds due to the `WaitForSingleObject` call. `Thread.yield()` feels to be a good way to go here.

**Comment by snazy** [comment]
change committed

**Comment by z7658329** [comment]
why AtomicLongUpdate  performs better than ReentrantLock？is there benchmark test? thank you
