### ISSUE TITLE
configurable byte order 

### ISSUE THREAD

**Issue by avukajlo** [snazy/ohc#29]
Is it possible to make byte order configurable (via cache builder) in OHC. Current implementations is hard coded to big endian.

**Comment by snazy** [comment]
to make the ByteBuffer API methods on the values use a configurable byte order?

**Comment by avukajlo** [comment]
I catch your point , thanks.

**Comment by snazy** [comment]
would be interesting to know whether it works.

**Comment by avukajlo** [comment]
seems that works :) thanks

**Comment by snazy** [comment]
TL;DR (for others possibly watching) you can set the byte order directly on the `ByteBuffer` object.
