### ISSUE TITLE
jvm core dump on large hash table size

### ISSUE THREAD

**Issue by avukajlo** [snazy/ohc#30]
test case:
OHCacheBuilder<String, String> builder = OHCacheBuilder.newBuilder();
builder.hashTableSize(1 << 30).build();
will result in 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000006b2e4cd1, pid=4088, tid=0x000000000000100c
#
# JRE version: Java(TM) SE Runtime Environment (8.0_102-b14) (build 1.8.0_102-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.102-b14 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0x274cd1]

due to bad cast from long to int in method
static Table create(int hashTableSize, boolean throwOOME)
        {
            int msz = (int) Util.BUCKET_ENTRY_LEN * hashTableSize;
            long address = Uns.allocate(msz, throwOOME);
            return address != 0L ? new Table(address, hashTableSize) : null;
        }
msz is not C* unsigned int, it should be long in java.

**Comment by snazy** [comment]
oops. that should not happen.
good catch!

**Comment by snazy** [comment]
Added a check to the offending cast and a couple of other possibly dangerous int-casts.
