### ISSUE TITLE
Evaluate TinyLFU

### ISSUE THREAD

**Issue by ben-manes** [snazy/ohc#34]
TinyLFU is an admission filter that improves the hit rates of caches by eagerly discarding entries with a low historic frequency. This differs from an eviction policy, which tries to organize entries to find a good victim but always accepts new entries into the cache. As many entries are low value, e.g. one hit wonders, this results in "cache pollution".

Policies like FIFO and LRU are the most susceptible to this by allowing new arrivals to flow through the entire cache before being evicted. Policies like SLRU, S4LRU, ARC, and LIRS try to reduce this by having a smaller "probation" period to monitor incoming entries for a second access, which promotes them to a "protected" region. To further increase hit rates, ARC and LIRS use ghost entries (evicted keys) to retain a longer history than the working set.

TinyLFU ([paper](http://arxiv.org/pdf/1512.00727.pdf)) retains its history more compactly through a `CountMinSketch`. Instead of retaining ghost keys on recency ordered lists, it hashes into a counter matrix and ages them periodically. This allows it to identify the "heavy hitters" in a stream of events and decide if the new arrival has a higher value than the eviction policy's victim by comparing their frequencies.

W-TinyLFU ([HighScalability article](http://highscalability.com/blog/2016/1/25/design-of-a-modern-cache.html) variant is a policy based on tuning using various simulations. It better copes with recency skewed traces by delaying the TinyLFU filter using an admission window. It then uses SLRU so that a better victim is chosen. In most workloads the simpler TinyLFU has equal performance, but for more robustness over a variety then the W-TinyLFU is recommended.

[Caffeine](https://github.com/ben-manes/caffeine) uses a 4-bit CountMinSketch. It does not use the paper's idea of a "doorkeeper", but does include it in the simulator. One or both of these could be ported easily. It is likely that only TinyLFU is needed in this cache's workload types, but if not then W-TinyLFU would require a little more work to integrate. However, either should not be difficult to add and test.

The benefit of this approach is quite [astounding](https://github.com/ben-manes/caffeine/wiki/Efficiency).

**Comment by snazy** [comment]
Took a stab on integrating W-TinyLFU in OHC. The concept of the three generations (eden, protected, probation) with the admission filter is clear and makes sense.

Work is still very much in progress and incomplete.
Branch: https://github.com/snazy/ohc/tree/window-tinylfu

**Comment by ben-manes** [comment]
Looking good. When you're ready, we can take a snapshot and run it through my simulator to verify similar hit rates.

Are you planning on switching to a 64-bit hash? I was limited by Java's 32-bit and a desire to not fork the hash table, but you aren't. So you could use your existing murmur hash and pass that through. I used a 32-bit version of H2's hash since its pretty good and fast. There's a 64-bit as well, though I think reusing your murmur hash is probably better.

You can drop the random seed, especially if using murmur. However you will want to adopt the [admit](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L638) function which better serves the same purpose. Thanks to your Cassandra colleagues for helping to iterate on that.

Is the use of an `Unsafe` counter table useful? Curious about the pros and cons.

**Comment by snazy** [comment]
Yes, I plan to use 64bit hashes.

Also force-pushed a new version of the branch. There are still a couple of TODOs in the code and it needs some benchmarking.

**Comment by snazy** [comment]
Alright, I think the implementation is ok so far.
Overhead from the JMH tests it looks that the perf penalty for W-Tiny-LFU is not much - so altogether it seems worth to consider W-Tiny-LFU as a better alternative. Although, I left the default untouched (i.e. LRU's the default).

Technically, the W-Tiny-LFU implementation has two LRU lists - one for the _eden_ and one for the _main_ generation. By default, _eden_ gets 20% of a segment's capacity and _main_ the remainder (i.e. 80%). When _eden_ needs eviction, entries in eden are checked against the _probation_ area using the `admit` function.

By default, the size of the admission filter is set to the size of the hash table (which defaults to 8192). There was no special reason to move the filter off-heap - initially I thought that the filter may become large (but it doesn't).

**Comment by ben-manes** [comment]
I added OHC to the simulator so that you can observe the hit rates. This should help to understand if there are differences between OHC and the stock algorithm and whether changes are beneficial. I liked to use the LIRS traces (in github) for variety, but they are small. For large, realistic workloads I use [ARC traces](http://researcher.watson.ibm.com/researcher/view_person_subpage.php?id=4700) (author's homepage). Let me know if you have any trouble using the simulator.

The limitation of the entry's size having to fit in the eden space is probably artificial. I'd have to work through my own logic, but I think I was careful to avoid that in my routine. Instead I always promote to probation and then evict from the main space by walking the lists. See [evictFromEden](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L499) and [evictFromMain](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L537) which should be more tolerant to various weight sizes. That might be useful to review.

I ran a quick test and the hit rate was a little lower than I expected. If I reduce the `window-tiny-lfu.percentMain` to `0.80` to mimic OHC, its similar. We should probably run through a bunch to verify expected behaviors.

**Comment by ben-manes** [comment]
One oddity is that `touch()` calls `frequencySketch.frequency()` instead of `increment()`. Not sure where the counters are increased.

**Comment by snazy** [comment]
> touch() calls frequencySketch.frequency() instead of increment()

Good catch. Fixed it.

Thanks for adding OHC to the simulator. Will look at it.

Regarding the "entry must fit in eden" topic:
What I was thinking about is for example this: Assuming a 1GB OHC instance and 16 segments -> 64MB per segment -> ~13MB eden size (20%). I think, it's a sizing / config thing related to capacity & number of segments (filed new issue #40).
If new "huge" entries are allowed to bypass eden (and therefore the admission filter),  the whole cache might be polluted.

From what I understood (please correct me, if I'm wrong):
- eden: new entries go here
- main / protected area: entries are "protected" against eviction
- main / probation area: entries in this area are subject of eviction (depending on the result of `admit()`)

My implementation to free space in main (i.e. when eden has not enough space for a new entry) is to check one entry in eden against one in main. The algorithm stops when either eden has enough capacity for the new entry (and the new entry can be placed ther) or the used capacity of the probation area has been processed (the new entry is rejected). Not sure about the latter case - but this was due to my understanding of the admission filter and probation area.

**Comment by ben-manes** [comment]
You're definitely correct. The algorithm doesn't take into account entry sizes and, like most other policies, assumes all are equal. So adapting it to varying weights requires a little creativity in finding whatever balance you prefer. There is no wrong answer, just gray areas.

In my approach I promote from eden until its within bounds. Then I evict from main until its within bounds, preferring to evaluate the victim to the promoted entries. This way a large entry flushes eden and itself into probation, the filtering proceeds, and if accepted then further evictions from the remaining space in main. This way multiple entries might be evicted if needed and a large entry would be kept if high value. The worst case of causing the eden space to flush seemed reasonable since I thought it would be a rare occurrence (and is only 1% in Caffeine). If the entry is too large for the cache to hold at all then it is rejected outright rather then flush the entire cache.

Any approach seems fine and probably behave the similar in real workloads. In the simulator some traces are small (e.g. 16k events) so shrinking your window to 1% resulted in no admissions (0% hit rate). But that's more of a limitation of what traces we have that demonstrate interesting pattern, rather than something you need to tune for.

**Comment by ben-manes** [comment]
I ran a few simulations and most look okay. However for some workloads the implementation is oddly worse than expected when comparing to W-TinyLFU @ 20%. I think these are modestly recency skewed and noticeably under performed at 512 entries.
- sprite, multi2, multi3 (lirs)
- OLTP (arc)

**Comment by snazy** [comment]
@ben-manes do you think the current implementation is good enough?

**Comment by ben-manes** [comment]
Yes. We can always iterate on it later. The two traces most likely workload to match a Cassandra workload are,

|Trace|OHC (LRU)|OHC (TinyLFU)|Caffeine|
|---|---|---|---|
|DS1 (Database)|20.24%|40.13%|44.98|
|S3 (Search)|12.04%|33.31%|42.87%|

Some of this is due to OHC using a 20% window, whereas Caffeine uses 1%. I have a [prototype](https://github.com/ben-manes/caffeine/blob/master/simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/sketch/climbing/SimpleClimber.java) that adapts the window by sampling the hit rate and using hill climbing to tune the size. This is working very well, as it corrects itself to match the recency or frequency bias of the workload. We might want to integrate that idea here too, once a full evaluation is completed.

**Comment by snazy** [comment]
Alright, then let's close this one.

**Comment by ben-manes** [comment]
closed but not merged?

**Comment by snazy** [comment]
ouch!

**Comment by snazy** [comment]
Thanks for the heads up. Pushed 0.6.1 to sonatype (takes approx a day until it's on maven central).
