### ISSUE TITLE
Simple put and get fails

### ISSUE THREAD

**Issue by davidhoyt** [snazy/ohc#41]
Thank you for your excellent work -- I have a simple test where I create a cache with all the default settings (using a string key/value serializer) and then do:

```java
cache.put("a", "exists");
assert(cache.get("a") != null);
```

Unfortunately doing a `get` right after a `put` sometimes works and sometimes doesn't. Am I misunderstanding how it should work?

If I place `put` in a loop then it works reliably:

```java
while (!cache.containsKey("a")) {
  cache.put("a", "exists");
}
```

However, it can take _several_ attempts before the entry is added. I'm using version 0.5.1 on OS X (Sierra), Oracle Java v1.8.0_112.

**Comment by snazy** [comment]
Thanks for reporting.
Can you provide a reproducible unit test?

**Comment by davidhoyt** [comment]
Do you have a gitter channel for a more in-depth discussion?

**Comment by davidhoyt** [comment]
Sorry about the noise -- I believe this issue was caused by our own `String` `CacheSerializer` which was exhibiting nondeterministic results.

**Comment by snazy** [comment]
Glad it's sorted out
