### ISSUE TITLE
malloc failures

### ISSUE THREAD

**Issue by davidhoyt** [snazy/ohc#42]
Running the basic tests in the develop branch on OS X (Sierra) with Oracle Java v1.8.0_112 results in errors like the following:

```
java(34125,0x700007944000) malloc: *** mach_vm_map(size=9223372036854775808) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
```

Is that expected? Are you malloc'ing a huge number on purpose perhaps?

**Comment by snazy** [comment]
That's expected and the correct outcome.
Unfortunately it's impossible to prevent that ugly message.

**Comment by lanpishu6300** [comment]
will it cause jvm crashes?
