### ISSUE TITLE
In constructor of OHCacheChunkedImpl when failed to init OffHeapChunkedMap ArrayIndexOutOfBoundsException is throw

### ISSUE THREAD

**Issue by churvey** [snazy/ohc#45]
line 105 , the index i can reaches to -1 which result in an ArrayIndexOutOfBoundsException. The code is 
{
 while (i-- >= 0)
    maps[i].release();
     throw e;
}
 it should be 
{
 while (i >= 0)
    maps[i--].release();
     throw e;
}

**Comment by snazy** [comment]
Good catch! Thanks for pointing this out.
That's obviously wrong.
I've copied the (correct) loop from `OffHeapLinkedMap` to make it look similar.
