### ISSUE TITLE
NullPointerException for OHCacheLinkedImpl.stats()

### ISSUE THREAD

**Issue by davidhoyt** [snazy/ohc#48]
Am seeing a `NullPointerException` for `OHCacheLinkedImpl.stats()` on line `706` for v0.5.1. This corresponds to line `716` in the develop branch. This is the code in question:

```java
        for (OffHeapLinkedMap map : maps)
            rehashes += map.rehashes();
```

`map` is `null` for some reason.

**Comment by snazy** [comment]
Can you provide a bit more detail on this?

**Comment by davidhoyt** [comment]
I have been trying to reproduce it as an isolated unit test but have thus far been unsuccessful.

**Comment by snazy** [comment]
Any luck to reproduce so far?

**Comment by snazy** [comment]
Closing due to lack of reproducible test case.
