### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()

### ISSUE THREAD

**Issue by maltalex** [snazy/ohc#70]
The official build of version 0.7.0 produces the following exception:

`java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;` when calling `serializeHotNEntries`.

It's actually a compilation issue experienced by many other projects:

https://github.com/hazelcast/hazelcast/issues/14214
https://github.com/plasma-umass/doppio/issues/497
https://github.com/functional-streams-for-scala/fs2/issues/1357
https://github.com/eclipse/jetty.project/issues/3244
https://github.com/apache/felix/pull/114

**Comment by snazy** [comment]
Should work now with the latest commits on the `develop` branch (needs to be built with j11 but can then run with j8).

**Comment by PuGuanyu** [comment]
> Should work now with the latest commits on the `develop` branch (needs to be built with j11 but can then run with j8).

Nice!And when will the new version release?

**Comment by snazy** [comment]
Sorry, quite late, but just released 0.7.1, which should not into this issue anymore.
