### ISSUE TITLE
looking forward to the new release

### ISSUE THREAD

**Issue by kfchu** [snazy/ohc#73]
0.7.0 is the latest release but already in 2018, so I am really looking forward to the new release which include the commits after 0.7.0.

**Comment by kfchu** [comment]
@snazy Hi, do you have plan to build a new release ?

**Comment by landawn** [comment]
@kfchu , maybe you could try Chronicle-Map: [](https://github.com/OpenHFT/Chronicle-Map)

**Comment by snazy** [comment]
Hi @kfchu just released 0.7.1, should be visible in Maven Central soon-ish.
